### ISSUE TITLE
Review and move griddistrict scripts 

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#10]
Scripts from section 'Griddistrict' need to be reviewed, adjusted and moved to the new repo: 

- [x] [ego_dp_mv_griddistrict.sql](https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/dataprocessing/sql_snippets/ego_dp_mv_griddistrict.sql)
  - [x] Count number of substations per municipality and store in table
  - [x] Apply use voronoi cells for municipalities of type 2 (with > 1 substations) and apply cutting
  - [x] Merge cut polygons with next neighboring municipality that has a substation
  - [x] Handle type 3 municipalities (those without a substation)
- [ ] [ego_dp_substation_id_to_generator.sql](https://github.com/openego/data_processing/blob/5edca414212ccb4b1df6b046bf916bc2ebb7b4c6/dataprocessing/sql_snippets/ego_dp_substation_id_to_generator.sql)

**Comment by gplssm** [comment]
Tables (former tables names of old data_processing) and related issues where these data are created in that this issue depends on.

For ego_dp_mv_griddistrict.sql

- model_draft.ego_grid_hvmv_substation, model_draft.ego_grid_hvmv_substation_voronoi #9 

For ego_dp_substation_id_to_generator.sql

- model_draft.ego_dp_supply_conv_powerplant
- model_draft.ego_dp_supply_res_powerplant

The latter script might be postponed a bit longer...

Next steps

- Understand more in detail how the method for creating MV grid districts work. Take also a look in Hülk et. al. 2017
- Decide if transfer to SQLAlchemy makes sense in order to reduce code repetition

**Comment by gplssm** [comment]
Cutting municipalities with voronoi polygons of HV-MV substations leads to one error that (in Schleswig-Holstein) rarely occurs

![grafik](https://user-images.githubusercontent.com/8255114/114054445-2c3f7180-9890-11eb-9dcb-52b809e4142e.png)

A tiny part of the cut municipality polygon is assigned to substation 23 while it is not touching any other polygon that's assigned to substation 23. Instead, it touches a polygon that was assigned to substation 22. Intuitively and visually, assigning this tiny polygon to substation would make more sense.

First, it needs to be answered if such polygons (more precisely multipolygons) with parts of the polygon that are not touching other parts occured in the MV grid district dataset that was used in open_ego.

Two options are available to achieve the visually more intuitive assignment to substation 22

1. Instead of assigning cut munipality polygon parts to the next neighboring polygon part that has a substation an iterative approach could be used: in each iteration cut polygon parts are assigned to the next neighboring polygon part that has a substation or that was already assigned to a polygon with a substation. This would only work if there are no fragemented multipolygons with non-touching parts.
2. Keep the present implementation a correct these error by updating the `subst_id` with the `subst_id` of a neighboring (and touched) polygon if none of the toughed polygons have the same `subst_id`.

**Comment by gplssm** [comment]
Approach 1 is favored.

Looking on a potential implementation, one more detail is important: 
In order to assign touching polygon successively to a polygon with a substation (and, starting from the 2nd iteration, also to already assigned polygons that don't have a substation initially) ST_Touches should be used. Once, there are no touching polygons anymore, while still polygons without a substation and without being assigned to a substation exist, ST_DWithin should be used (as right now). This makes sure all polygons without a substation get assigned to substation in the end. This can be considered as two separate phases of substation assignment.
