### ISSUE TITLE
Clarify metadata format

### ISSUE THREAD

**Issue by EvaWie** [openego/eGon-data#139]
If I am not mistaking, we follow the [OEP Metadata version 1.4.0](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v140/metadata_key_description.md).
Nevertheless, there seem to be some unclear points regarding the creation of metadata:
- How do we reference datasets, which have been created / loaded by other scripts into the local database?
- Which date is dataset creation date? How is that related to the version control of our datasets?

Please feel free to add further points.

**Comment by nesnoj** [comment]
> If I am not mistaking, we follow the [OEP Metadata version 1.4.0](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v140/metadata_key_description.md).

The current version is [v1.4.1](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v141/metadata_key_description.md).

> Nevertheless, there seem to be some unclear points regarding the creation of metadata:
>
>     * How do we reference datasets, which have been created / loaded by other scripts into the local database?

Could you give an example? Maybe something like the RE potential areas, which were created at RLI but only loaded into the DB eGon-data?
From my point of view, all parts of the meta data should be filled but a single entry in 14 (`sources`) should be sufficient for the original data. Caution: mind the licenses due to redistribution.

>     * Which date is dataset creation date?

I assume you mean no 7 `publicationDate`. I'd use the date of PR merge and add entries to 13 (`contributors`) on updates. Also, we could reset all `publicationDate` as soon as eGon-data is finalized.

> Please feel free to add further points.

Would it be helpful to have a template?

**Comment by gplssm** [comment]
OEMetadata claims to be compatible with [frictionless data](https://frictionlessdata.io/). 

While creating metadata for [open-MaStR data](https://sandbox.zenodo.org/record/740153), I could not validate the metadata using  `frictionless validate`. A quick look on the specs of both shows differences in field names.

Questions:

- Is  OEMetadata compatible with frictionless?
- If not, is there a mapping?
- (If we need to decide) What is preferable? OEMetadata or frictionless?

**Comment by EvaWie** [comment]
> The current version is [v1.4.1](https://github.com/OpenEnergyPlatform/oemetadata/blob/develop/metadata/v141/metadata_key_description.md).

Thanks for the hint!

> Could you give an example? Maybe something like the RE potential areas, which were created at RLI but only loaded into the DB eGon-data?
> From my point of view, all parts of the meta data should be filled but a single entry in 14 (`sources`) should be sufficient for the original data. Caution: mind the licenses due to redistribution.

I was thinking of the procedure to reference datasets like vg250 and census tables, which are used as inputs for new tables. It should be avoided that we copy the information from the metadata of these input datasets into the new tables' metadata. Therefore, we try to implement a solution, that comes with the redesign of the datasets.yml.

**Comment by ClaraBuettner** [comment]
Here you can find the dataset configuration for the substation creation: https://gist.github.com/ClaraBuettner/400a238baa3fc749fe5bec3b6261ae17
