### ISSUE TITLE
Drop support for Python3.6

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#148]
There are functions which fail with python3.6 (see #104) but it is still included in the setup.py and the automatic test. This should be resolved.

- [x] remove python3.6 from setup.py
- [ ] remove python3.6 from github-actions
- [ ] remove python3.6 from tox testing

**Comment by ClaraBuettner** [comment]
I think I was also able to remove Python3.6 from tox testing and GitHub actions. The tox testing seem to work, but I don't know how I can test the GitHub actions without creating a PR.

**Comment by gplssm** [comment]
> I think I was also able to remove Python3.6 from tox testing and GitHub actions. The tox testing seem to work, but I don't know how I can test the GitHub actions without creating a PR.

Thanks for doing all this! :clap: 
It's totally fine to create a PR in order to test the GitHub actions workflow. If you are in a situation you want to do this but you aren't finished with the feature, simply mark the PR as "draft" and everyone knows it's work in progress. It might be still valuable for others to see the coming changes in a PR.
