### ISSUE TITLE
Task import-heat-demand fails with --dataset-boundary=Everything

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#204]
The heat demand import fails with the following log, the log file is ~4GB so I wasn't even able to open it completely, but this screenshot shows the most important lines (just the huge list of values is missing). 
![log_import-heat-demand](https://user-images.githubusercontent.com/22964326/114145178-6fdcbe80-9916-11eb-8ecb-561a7b7b286c.png)

It looks the these lines need too much memory: https://github.com/openego/eGon-data/blob/64b79217c5a203aa5b9278d6be8c3586f5c4005f/src/egon/data/importing/heat_demand_data/__init__.py#L478-L489

I think we can't really change something in these lines to reduce the memory because it is already directly inserted to the database. 
But regarding htop, the maximal RAM used is ~20GB and the server has much more.
@gnn Is there a limit for airflow or the docker container and could we try to adjust this?

**Comment by EvaWie** [comment]
I do not have a deep understanding of the reported problem. I just want to tell you, that I successfully run the heat demand data import for Germany, before we implemented the test case and the new docker container (and a few heat demand table related changes e.g. version numbering) on my laptop. Maybe this hint helps.

**Comment by gnn** [comment]
Thanks for the hint, @EvaWie . This is strange. It seems that the culprit is the [line importing the rasters][0]. This executes a SQL script which inserts a row that is simply to large for PostgreSQL. The whole raster_data is saved in one row and single objects like row entries are only allowed to be up to 1GB (=1073741824 Bytes) big, which the value in the log messages exceeds. So we either have to find a way of splitting the rasters into more than one row, or we'll have to find a way of storing the rasters as ["large objects"][1]. When implementing the raster import, I actually experimented a bit with storing the rasters in more than one row, so I might be able to dig up some code which could help here.
The only strange thing is, that it worked previously. Did we get more rasters with heat demand data for some reason?

[0]: https://github.com/openego/eGon-data/blob/64b79217c5a203aa5b9278d6be8c3586f5c4005f/src/egon/data/importing/heat_demand_data/__init__.py#L489
[1]: https://www.postgresql.org/docs/current/lo-intro.html

**Comment by EvaWie** [comment]
> I remember that we have changed the datatype from int to float. If that was done after Evas run, this could cause the difference and also the new issue. I will check if it works to import the values as integers.

That is a very good point!

**Comment by ClaraBuettner** [comment]
I tried to run it with Integer values and it worked. So we know at least why this error didn't occurred before. 
@gnn: It would be great if you could find the old code snippets for storing the raster in more than one row. If you send them to me I can try to implement it.

**Comment by gnn** [comment]
> I tried to run it with Integer values and it worked. So we know at least why this error didn't occurred before.

Nice.

> @gnn: It would be great if you could find the old code snippets for storing the raster in more than one row. If you send them to me I can try to implement it.

It's not much. I think it would be enough to use the `-t` switch documented in `raster2pgsql`'s [documentation][0]. So something like adding a `["-t", "auto"]` to [line 479][1]. The hard part is testing that this actually creates the same raster so it doesn't modify the results obtained from using the it.

[0]: https://postgis.net/docs/using_raster_dataman.html
[1]: https://github.com/openego/eGon-data/blob/64b79217c5a203aa5b9278d6be8c3586f5c4005f/src/egon/data/importing/heat_demand_data/__init__.py#L479
