### ISSUE TITLE
Allow for custom docker image location

### ISSUE THREAD

**Issue by nesnoj** [openego/eGon-data#228]
It'd be great to allow for a custom location where the docker image is to be stored, [docker-compose](https://docs.docker.com/compose/reference/) allows to do so.
Could we add a CLI option for this, what do you think @gnn ?

**Comment by gnn** [comment]
Do you mean the location of the docker image or the location where database data is stored? I changed the latter in PR #230. The PR stores database data in the current working directory under `"docker/database-data"`. Adding a command line parameter for this is also possible but might take a bit longer because of other issues. Changing the location of the actual docker image might also be possible, but I'd have to read more documentation in order to be sure and to know how to do this.
@gplssm: I changed the first commit on the `"features/#228-make-database-data-storage-location-configurable"` branch because I forgot to commit some changes before pushing. I force pushed the new commit, for once, so if Git will probably complain when you try to pull from the branch. Hope that's OK this one time.

**Comment by nesnoj** [comment]
Thanks @gnn for your quick measures!
As there's a vivid discussion with @gplssm in #230 I'll leave this one to him..
