### ISSUE TITLE
Find consistent spelling for ego_n and egon-data

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#27]
Right now we are using different ways of spelling ego_n and egon-data. 
I found for example the following 
* egon-data (repo)
* eGo^N data 
* eGon_data 
*...
We should agree on a consistent spelling for the documentation. Any opinions?

**Comment by gplssm** [comment]
Vote: egon-data

**Comment by gnn** [comment]
I don't think there's a single solution, because for me, different spellings mean different things:

  1. "eGo^N", or "egon" when I'm to lazy/tired to type complex stuff, is the name of the project.
  2. `egon.data`: is the name of package and the module that gets imported.
  3. `egon-data`: is the name of the command line tool, that gets installed when one does `pip install egon.data`. 

I'd also like to use these spellings consistently, but all of them, are up for grabs. For the project name, I'll use whatever spelling somebody tells me to use. For the command line application, we could also install an `eGon` command and make `data` a sub-command of that. We could even call it `eGo^N` since `^` isn't a reserved character in Bash. Dunno about Windows though, and I'm more inclined to keep things simple. Last but not least we could even still change the package name.
But the 2 and 3 are my votes and 1 is more of a "I thought that's the correct spelling" thing.

**Comment by gplssm** [comment]
> For me, different spellings mean different things:
> 
>     1. "eGo^N", or "egon" when I'm to lazy/tired to type complex stuff, is the name of the BMWI project.
> 
>     2. `egon.data`: is the name of package and the module that gets imported.
> 
>     3. `egon-data`: is the name of the command line tool, that gets installed when one does `pip install egon.data`. It's also the repository, but I think this can mostly be disambiguated via context.
> 
> 
> I'd also like to use these spellings consistently, but all of them are up for grabs. For the project name, I'll use whatever spelling somebody tells me to use. For the command line application, we could also install an `eGon` command and make `data` a sub-command of that. We could even call it `eGo^N` since `^` isn't a reserved character in Bash. Dunno about Windows though, and I'm more inclined to keep things simple. Last but not least we could even still change the package name.
> Long story short, 2 and 3 are my votes and 1 is more of an "I thought that's the correct spelling" thing.

Makes sense! I would like to follow the proposed convention.

For referring to the project itself, I would like to use eGo^n consistently.
