### ISSUE TITLE
Municipalities without mv grid

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#279]
There are two municipalities in Bavaria (namely Egloffstein and Hausen b. Würzburg) that don't belong to any mv grid. 
Both municipalities are also missing in boundaries.vg250_gem_clean which is an input to the mv grids. 
 I tried to look into the SQL script and stumbled over these lines: https://github.com/openego/eGon-data/blob/5dbaf24fc4cbb1300826d3684d0a47aa74292e7e/src/egon/data/processing/vg250/cleaning_and_preparation.sql#L564-L566
and I'm wondering if these might be the two municipalities which are deleted manually. 
@gplssm Why are these municipalities deleted manually from boundaries.vg250_gem_clean?

**Comment by gplssm** [comment]
I didn't came across these two municipalities. Honestly, I took this code from open_ego without changing it. It would like to try to remove this delete case or replace it with a smarter function in order not to lose these two municipalities. 
Sadly, I wasn't able to set up a second workflow for eGon-data to run it with `dataset=Everything` for testing, because it somehow conflicted with the existing container :-/.
I can't verify at the moment that these two municipalities have the ids  '9251' and '8362'. But it seems plausible. Are you anyways about to run the workflow again for Germany? Then, it would be great if you could delete these two lines and see if

1. The two above mentioned municipalities get associated to MV grid
2. If the downstream tasks don't fail on the changed VG250 data

**Comment by ClaraBuettner** [comment]
> Sadly, I wasn't able to set up a second workflow for eGon-data to run it with `dataset=Everything` for testing, because it somehow conflicted with the existing container :-/.

I also had those problems, it can be prevented by using the same container for different databases or rename the service (I don't really know why this helped but it was working..) 

> I can't verify at the moment that these two municipalities have the ids '9251' and '8362'. But it seems plausible. Are you anyways about to run the workflow again for Germany? Then, it would be great if you could delete these two lines and see if
> 
>     1. The two above mentioned municipalities get associated to MV grid
> 
>     2. If the downstream tasks don't fail on the changed VG250 data

I tested it on the server, the two municipalities have the ids '9251' and '8362'. 
If I remove` OR id = '9251' OR id = '8362';`, all municipalities are inside a MV grid and all downstream tasks run successfully.
