### ISSUE TITLE
Gas voronoi polygons without bus_id

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#362]
Some gas voronoi polygons have `bus_id = NULL ` which results in errors in `assign_gas_bus()`. 
Only polygons at the borders are effected. The closest gas bus for these polygons is located slightly outside of Germany, e.g. here at the border to the Netherlands (German borders in orange, gas voronoi without bus_id in green and gas buses with their bus_id) : 
![Bildschirmfoto vom 2021-08-03 15-29-57](https://user-images.githubusercontent.com/22964326/128023885-c8e846b0-2d49-4d43-b624-96d30421bfb8.png)

This happens only for gas voronoi outside of Schleswig-Holstein so the problem doesn't occur in the test mode.

**Comment by AmeliaNadal** [comment]
I think that the problem was also concerning the test mode so I took me a bit langer that what I thougt.
[This commit](https://github.com/openego/eGon-data/commit/1c1108553823128571baab407e6e15460e718808) should fix the bug. I made a [pull request](https://github.com/openego/eGon-data/pull/369) and requested you as rewier @ClaraBuettner.
