### ISSUE TITLE
Connect to docker database via pgAdmin

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#38]
I would like to be able to visualize the data via pgAdmin. I already connected to the dockerd database with my existing pgAdmin3 client. The connection is successful, I can see the schema I created, but I'm not able to see any data, I get the following error:
```
ERROR:  column "proisagg" does not exist
LINE 9:  WHERE proisagg = FALSE AND pronamespace = 17394::oid
```
I googled this problem and found out that the postgresql-version of the docker-database (12.4) is not compatible to pgAdmin3. 
Upgrading to pgAdmin4 would solve the problem. The website of pgAdmin4 says that it could be installed in a docker as well. 
I'm not familiar to this environment but would it be possible to integrate pgAdmin4 directly in the docker with the database?

**Comment by gplssm** [comment]
I'm using pgAdmin4 install via `apt install pgadmin4`. I've never thought about using pgadmin4 with docker.
Does anything speak against installing pgadmin4?

**Comment by ClaraBuettner** [comment]
> I'm using pgAdmin4 install via `apt install pgadmin4`. I've never thought about using pgadmin4 with docker.
> Does anything speak against installing pgadmin4?

Nothing really speaks again installing pgAdmin4. I was just wondering if it would be easier to integrate it directly in docker. I can also install pgAdmin4 manually.

**Comment by gnn** [comment]
My initial reaction was to rather have pgAdmin4 installed locally, too. But that's mainly because I'm used to pgAdmin3 which uses a GUI that would be hard to use via Docker. As pgAdmin4 uses a web application as its GUI, it would actually be possible to serve that application from the Docker container. The benefit would be that anybody could just look into or manage the local database via his browser without installing any additional software. Also, configuring database access could just be done from the configuration of the local database. So I think if we find a way of installing and configuring pgAdmin4 on the Docker container, that might be a feature which is "nice to have". I wouldn't be against it, but I probably won't have time to implement this in the next two weeks at least.
