### ISSUE TITLE
Integrate scripts on demographic change

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#47]
We need to integrate the scripts which were created by our student to create a projection of population and household per 100mx100m grid into the workflow. 
This includes some necessary changes and adjustments in the code

- [ ] rework and speed up SQL statement to match zensus grid cell and administrative district 
- [ ] add a buffer or some such to be able to catch zensus point which are located outside the disctrict polygons
- [ ] rework python scripts to read data from local db instead of csv

**Comment by ClaraBuettner** [comment]
I pushed the match of zensus cells to nuts3 with geopandas in the corresponding branch. It seems to be much faster but needs more RAM. With 16GB RAM I could only run the function for a subset of the data (~5*10^6 cells, execution time 20min) which is why the SQL select statement is currently limited. When the testcase is there I will remove that. 

It also includes a method to match cells outside of the boundaries which seems to work fine. I visualized the nuts3 regions of the zensus cells in the North Sea which have the largest distance to nuts3 regions:
![nuts3_zensus_match](https://user-images.githubusercontent.com/22964326/108207177-ad4b7980-7127-11eb-8f00-44d57e0f41b9.png)

**Comment by IlkaCu** [comment]
That looks good. Thanks a lot!

**Comment by ClaraBuettner** [comment]
The population and household prognosis is integrated. I manually applied the function only on cells in Schleswig-Holstein until the test case is integrated.
Before I open a PR I would like to use the test case and also test for whole Germany on the server which is currently not available.
