### ISSUE TITLE
Docker image of postgres container might be build too often

### ISSUE THREAD

**Issue by gplssm** [openego/eGon-data#52]
In `initdb()` the postgres database is created using `docker-compose up -d --build`. The option `--build` forces docker to rebuild the image, even if not necessary. Without that flag, the image is build when it's no present, for example on the first run.
I suggest to remove this option. @gnn any concerns?

**Comment by gnn** [comment]
In our case, rebuilding the image also means running `apt-get update` and `apt-get install -y postgresql-12-postgis-3` inside the container. And I think it also means that updates to the parent container, i.e. `postgres:12` will be picked up, but I might be wrong on that. So with the flag, `egon-data` runs will always use the newest `postgres:12` and `postgresql-12-postgis-3` versions, which might lead to the data processing pipeline suddenly breaking for a user, even without changes to the code.
Without the flag though, all of us might work with an old container using old software, while updates broke the processing pipeline without anybody noticing. So I guess I'm in favour of removing the flag, but making sure that container and local database usage is tested, so that continuous integration has a chance to detect when software updates break our pipeline.

**Comment by gplssm** [comment]
> In our case, rebuilding the image also means running `apt-get update` and `apt-get install -y postgresql-12-postgis-3` inside the container. And I think it also means that updates to the parent container, i.e. `postgres:12` will be picked up, but I might be wrong on that. 

I think you're right, the image gets re-build (the `Dockerfile.postgis`) and subsequent Dockerfiles are run. 

> So with the flag, `egon-data` runs will always use the newest `postgres:12` and `postgresql-12-postgis-3` versions, which might lead to the data processing pipeline suddenly breaking for a user, even without changes to the code.

Also true! We could achieve roughly the same with using `image: "postgres:latest" with the advantage of having always the most up-to-date version. But we would also switch to Postgres 13 which might challeng people like me who are still using 18.04.

> Without the flag though, all of us might work with an old container using old software, while updates broke the processing pipeline without anybody noticing. So I guess I'm in favour of removing the flag, but making sure that container and local database usage is tested, so that continuous integration has a chance to detect when software updates break our pipeline.

If I get you right, we could write a test that initializes the database and we covered most of it. This would also be helpful for testing our data processing functions, because we could use the once set up database then.

**Comment by gplssm** [comment]
After using it for a longer time, I realized I'm fine with it. Please reopen if this issue re-occurs.
