### ISSUE TITLE
Missing input values for eTraGo in eGon2035 scenario

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#538]
Some input data in the eTraGo-tables is missing/incomplete which currently results in error when running eTraGo. 
I run the CI-branch from last Friday to create the data model. The following values have to be adjusted to run eTraGo:

- [x] CH4 and H2 loads currently have `sign = NaN`, which breaks the optimization. This should be adjusted to `sign = -1` (@AmeliaNadal , @fwitte)
- [x] H2-to-CH4, CH4-to-H2 and H2-feedin links have no `p_nom = NaN`. If they are not always extendable, these values have to be added. If they should be optimized in every calculation it could be also possible to set `p_nom_extendable` and `capital_costs` (@AmeliaNadal , @fwitte)
- [x] `rural` heat loads are attached to the `AC` buses (@ClaraBuettner )

**Comment by fwitte** [comment]
The information for capital_cost, efficiency and marginal_cost of all gas related technologies will be written into the carrier table. I will open a PR to deal with these tasks.

- [ ] capital_costs
- [ ] marginal_costs
- [ ] efficiencies

The capital costs for saltcavern storage could/should be modified according to its integration in the datamodel (own H2 bus or connected to CH4 grid related H2 bus via pipeline due to proximity to gas nodes, see https://github.com/openego/eGon-data/issues/537). Slightly higher specific cost than storage only would be considered in this case.

**Comment by AmeliaNadal** [comment]
The first point should be solved with PR https://github.com/openego/eGon-data/pull/539.

**Comment by fwitte** [comment]
I added the missing p_nom_extendable column in all three tables (#478), the final capital_cost data will be integrated in a different PR.

**Comment by fwitte** [comment]
I think we can close this one @ClaraBuettner on merge of #608
