### ISSUE TITLE
Clean up "pipeline.py"

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#562]
The `pipeline.py` looks a bit messy by now. Some needless leftovers, like unused dependency definitions, caused by the restructuring should be removed.

**Comment by nailend** [comment]
The `PythonOperator` used here are necessary even if the look like from old times. @gnn maybe you know a better way to to this.
The Problem is, that a function is called this with different parameters. You can also do it with `func_tool.partial` but it doesnt copy `__module__` and `__name__` attributes of the inner function [see here](https://github.com/elastic/apm-agent-python/issues/293), which can be patched but doesn't look nice either.

**Comment by gnn** [comment]
There are multiple ways of fixing this, but first things first: I think the lines you tried to link shifted, @nailend. The "pipeline.py" file changed and since your link always points to whatever `dev` currently points to, the line numbers are no longer correct. In order to avoid this, hit the "y" key while on a page displaying a file. Then the URL will change to incorporate the ID of the commit you're currently looking at, making the link absolute. Example: I think you meant [these lines][0], amiright?
 
Now for the fixes: I published an example on the ["scratchpads/move-operators-out-of-the-pipeline"][1] branch. Would you be so kind to test out whether this actually works? I didn't get around to test this. If this works, another, more clunky fix would've been to define two functions like this:

```python
def mv_hh_electricity_load_2035():
    mv_grid_district_HH_electricity_load("eGon2035", 2035, drop_table=True)


def mv_hh_electricity_load_2050():
    mv_grid_district_HH_electricity_load("eGon100RE", 2050)
```

and simply use those in the task list. There are a few other ways to polish this, but first I need to know whether my fix works. If that's the case, we'll commit a better fix on a different branch. 

[0]: https://github.com/openego/eGon-data/blob/e82acd887655a5e0460b09bf5a4816410cf731b8/src/egon/data/airflow/dags/pipeline.py#L291-L302
[1]: /openego/eGon-data/tree/scratchpads/move-operators-out-of-the-pipeline

**Comment by nailend** [comment]
@gnn thanks for this idea! It works! I will open up a separate issue and apply your fix  on a new branch.

**Comment by gnn** [comment]
Thanks. Good to know that it worked. Now that I had some time to ponder over the code, I actually don't think that the two functions are that clunky, if done right. I'll push a few corresponding commits to a proper `"features/"` branch tomorrow, i.e. on Wednesday.
