### ISSUE TITLE
Copying data from a file to docker db fails

### ISSUE THREAD

**Issue by IlkaCu** [openego/eGon-data#80]
Running the following code within our workflow and directly from pgAdmin4 fails: 
`COPY society.destatis_zensus_population_per_ha (grid_id, x_mp, y_mp, population) 
FROM '{os.path.join(os.path.dirname(__file__), filename)}' 
DELIMITER ';'
CSV HEADER; `

The same happens when including the 'real' filepath.

Error message: 

ERROR:  could not open file "/eGon-data/src/egon/data/importing/zensus/Zensus_Bevoelkerung_100m-Gitter.csv" for reading: No such file or directory
TIP:  COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.
SQL state: 58P01
Hint: COPY FROM instructs the PostgreSQL server process to read a file. You may want a client-side facility such as psql's \copy.

**Comment by gplssm** [comment]
The postgres database runs in the container that is provided with docker. Docker provides a sandboxed environment with limited access to files on the actual computer where docker is executed. In order to access files on the computer, those must be provided as [docker volume](https://docs.docker.com/storage/volumes/).

If you would like to insert data with `COPY` you would have to "mount" this data with a volume.
As an alternative you could use other methods to insert/copy data into the database. For example, I used Geopandas' `to_postgis()` for [vg250](https://github.com/openego/eGon-data/blob/e8301014fb6c8826452c72331e6c9d2cd153934b/src/egon/data/importing/vg250.py#L69-L77).
I would recommend to use such an approach.

Is this one for the FAQs?

**Comment by gnn** [comment]
Guido is correct with his assessment of the reason for the error. The path to the CSV file is a path on your computer, whereas the docker container is basically a differen't computer an which the given path probably doesn't exist. Since the query is executed inside the container, the file can't be found.

> As an alternative you could use other methods to insert/copy data into the database.

Fortunately there is an easy alternative. The `psql` tool has a `\copy` command, which, if I'm correct, has the same syntax as SQL's `COPY` statement but accesses files on the machine on which `psql` was invoked and sends the data to the database. On top of that, one can execute commands via `psql` non-interactively using the `-c` command line switch. So you would have to do something like:
```
subprocess.run(
    ["psql", "-c", "\copy ..."]
)
```

where you can replace `...` with what comes after the `COPY` in your query. Obviously you'd also have to supply database connection information to `psql` and I currently don't have the time to look up how to do that exactly.

> Is this one for the FAQs?

Probably.

This also would introduce an external dependency on `psql` which is provided by `postgresql-client-common` on Ubuntu 20.04.

**Comment by IlkaCu** [comment]
The solution gnn suggested works fine and is implemented in PR #90
