### ISSUE TITLE
ModuleNotFoundError: No module named 'pytest'

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#801]
eGon-data is not running on current dev branch. Manually installing `pytest` using pip solved the problem. 
@nesnoj: It seems to be caused by the e-mob branch. Could you solve this? 
```

 File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/clara/test-egon-data/eGon-data/src/egon/data/airflow/dags/pipeline.py", line 27, in <module>
    from egon.data.datasets.emobility.motorized_individual_travel import (
  File "/home/clara/test-egon-data/eGon-data/src/egon/data/datasets/emobility/motorized_individual_travel/__init__.py", line 95, in <module>
    from egon.data.datasets.emobility.motorized_individual_travel.ev_allocation import (
  File "/home/clara/test-egon-data/eGon-data/src/egon/data/datasets/emobility/motorized_individual_travel/ev_allocation.py", line 29, in <module>
    from egon.data.datasets.emobility.motorized_individual_travel.tests import (
  File "/home/clara/test-egon-data/eGon-data/src/egon/data/datasets/emobility/motorized_individual_travel/tests.py", line 6, in <module>
    import pytest
ModuleNotFoundError: No module named 'pytest'
```

**Comment by nesnoj** [comment]
Hey, oh I thought pytest is part of the requirements already as @gnn also makes use of it [here](https://github.com/openego/eGon-data/blob/dev/tests/test_egon-data.py#L4). I added it to skip a certain test the same way to make the testing happy.
Could you please drop a note @gnn?

**Comment by gnn** [comment]
So, the place I'm using "pytest" is part of the tests. These are not actually part of the installed package, i.e. it's not code which can be reached and run by standard means if you install the package. That's why "pytest" isn't part of the requirements already. It is part of the `dev` extra requirements, though. So if you do `pip install .[dev]`, or `pip install egon-data[dev]` once the package has it's first release, "pytest" gets installed. The reason for this is simple: a normal user usually doesn't have a reason to run the tests, whereas a developer should run them. And the `dev` extra requirements are meant to pull in all packages needed for development in addition to the regular requirements.

> The test function `test_ev_numbers()` is for use within the task and requires the DB so I had to mark it to be skipped to make the actions testing happy. Is there a better approach on this @gnn or can we add pytest to the reqs?

I don't know whether I correctly understand that sentence. Do you mean that the tests unintentionally pick up the `test_env_numbers()` function and try to run it as a test? If so, this can most easily be fixed by renaming the function. Since the docstring starts with "Validate", the most straightforward solution would be to call it `validate_electric_vehicle_numbers`. If I understood the problem correctly, that is.

And while I'm at it, some (very) minor points:
  * Having [`test_ev_numbers()`](https://github.com/openego/eGon-data/blob/042172cca7133e5911ee5095d35eb37ce2f4eedf/src/egon/data/datasets/emobility/motorized_individual_travel/tests.py#L16) be a link to its definition saves me a bit of time. ;) I know it's just a few seconds because of GitHub's awesome search function, but I first had to figure out how that works again.
  * Please don't use abbreviations like "ev". When I first saw this, I thought it meant "environment". There's no reason not to use "electric_vehicles" instead. And if the variable names get too long, that's a good hint that you should refactor your code to put some of the long names into dedicated methods, classes, modules or similar. There's also a nice [post](https://chrisdone.com/posts/german-naming-convention/) on why not using abbreviations improves readability. It's less than a five minute read and it's even referenced in our [contribution guidelines](https://github.com/openego/eGon-data/blob/dev/CONTRIBUTING.rst#code-and-commit-style).
  * The correct abbreviation for Not a Number is ["NaN"](https://en.wikipedia.org/wiki/NaN).
  * From Python's [Docstring Conventions](https://peps.python.org/pep-0257/#one-line-docstrings) on one-liners:
    > The docstring is a phrase ending in a period.

    I know, Git and Python having different conventions for this is whack. Sorry for this.

**Comment by gnn** [comment]
Oh and yes, we could potentially add "pytest" to the requirements. But I'd rather avoid that if possible, as our requirements are already rather heavyweight.

**Comment by nesnoj** [comment]
Thanks a lot for your very extensive answer @gnn !

> > The test function `test_ev_numbers()` is for use within the task and requires the DB so I had to mark it to be skipped to make the actions testing happy. Is there a better approach on this @gnn or can we add pytest to the reqs?
> 
> I don't know whether I correctly understand that sentence. Do you mean that the tests unintentionally pick up the `test_env_numbers()` function and try to run it as a test? If so, this can most easily be fixed by renaming the function. Since the docstring starts with "Validate", the most straightforward solution would be to call it `validate_electric_vehicle_numbers`. If I understood the problem correctly, that is.

You got that right, I renamed the function in afb8adb1ea0f5fda41a05bf6321aa1bf69475e22 and kicked out pytest - github action tests in #588 now work out without the marker.

> And while I'm at it, some (very) minor points:
> 
> * Having [`test_ev_numbers()`](https://github.com/openego/eGon-data/blob/042172cca7133e5911ee5095d35eb37ce2f4eedf/src/egon/data/datasets/emobility/motorized_individual_travel/tests.py#L16) be a link to its definition saves me a bit of time. ;) I know it's just a few seconds because of GitHub's awesome search function, but I first had to figure out how that works again.

I don't understand what you mean by "be a link to its definition".

**Comment by nesnoj** [comment]
I hotfixed it into `dev`
