### ISSUE TITLE
Missing flake8 config

### ISSUE THREAD

**Issue by khelfen** [openego/eGon-data#807]
At the moment there is no config for `flake8`. Since black uses 88 characters by default and `flake8` uses 79 characters, this leads to incompatibility. The `.flake8` file should at least include:

```
[flake8]
max-line-length = 88
```

**Comment by khelfen** [comment]
@gnn I have created a proposal and opened a PR. See #810

**Comment by khelfen** [comment]
@gnn Any update here?

**Comment by gnn** [comment]
Sorry, but I missed this issue. There is no configuration for flake8 because the defaults are fine. There is however a configuration for black in "pyproject.toml" because the black developers decided that this is the only place from which they read configuration settings. And that's where the maximum line length is set to 79 characters for black because that's in line with PEP8.

**Comment by khelfen** [comment]
Thanks @gnn ! Actually when running `black` per `hook` or directly in the console it seems like it is not respecting the 79 char limit but still formats everything to 88 chars for me :thinking: That's why I got these incompatibilities.
