### ISSUE TITLE
How to add git-dependencies to setup.py?

### ISSUE THREAD

**Issue by ClaraBuettner** [openego/eGon-data#89]
I'm trying to integrate our fork of demandregio's disaggregator into the workflow. I wonder how I should add this dependency to the setup.py. The former `dependency-links` are deprecated in newer versions of pip. Alternatively, I could add  `disaggregator @ git+https://github.com/openego/disaggregator.git` to `install_requires`. 
But currently there are two problems with this option. First, the disaggregator can not be installed with pip and has no setup.py. I can fix this on our fork, so that's not a big problem. 
The other one seems more complicated to me: in our last eTraGo-release we tried to use the above described `install_requires` but couldn't release on pypi (`ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI`.). @gnn do you know if we plan to release egon-data on pypi and have an idea how to fix this?

**Comment by gplssm** [comment]
> I'm trying to integrate our fork of demandregio's disaggregator into the workflow. I wonder how I should add this dependency to the setup.py. The former `dependency-links` are deprecated in newer versions of pip. Alternatively, I could add `disaggregator @ git+https://github.com/openego/disaggregator.git` to `install_requires`.

Thanks for figuring this out :+1:

> But currently there are two problems with this option. First, the disaggregator can not be installed with pip and has no setup.py. I can fix this on our fork, so that's not a big problem.

I agree. We can work around that with your proposed solution!
In addition to that, I would like to feed these changes back to the original disaggregator repo. I can help on that one.

> The other one seems more complicated to me: in our last eTraGo-release we tried to use the above described `install_requires` but couldn't release on pypi (`ERROR: Packages installed from PyPI cannot depend on packages which are not also hosted on PyPI`.). @gnn do you know if we plan to release egon-data on pypi and have an idea how to fix this?

True!
Yes, we plan to release on PyPI. And, as far as I understood it, we need the disaggregator package being published on PyPI. If we need to use the fork for eGo^n because we have to many changes which can't be fed back to the original repo, we must publish the forked disaggregator package on PyPI by ourselves. This requires that the original disaggregator repo has an appropriate license.

**Comment by ClaraBuettner** [comment]
I looked at some other packages we want to integrate later on. At least some of them (glaes for the potential areas, pypsa-eur and pypsa-eur-sec) are also not published on pypi. So I'm wondering if we can and want to publish all of them on pypi. What do you think?

**Comment by gnn** [comment]
Hm. If things like this keep piling up, I'd rather vote for treating them the same as system dependencies and document them in the installation instructions so users have to install them manually. Especially if some of them aren't packaged with a "setup.py" file or similar mechanism. If we document them with a note like "Since package XYZ isn't published on PyPI, you have to install it manually from source, available at ...", maybe this makes users contact the devs or file an issue so that the packages eventually get published.
